// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_stream.proto

#include "server_stream.pb.h"
#include "server_stream.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace serverstream {

static const char* StreamServer_method_names[] = {
  "/serverstream.StreamServer/ListValue",
};

std::unique_ptr< StreamServer::Stub> StreamServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StreamServer::Stub> stub(new StreamServer::Stub(channel, options));
  return stub;
}

StreamServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListValue_(StreamServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::serverstream::StreamResponse>* StreamServer::Stub::ListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::serverstream::StreamResponse>::Create(channel_.get(), rpcmethod_ListValue_, context, request);
}

void StreamServer::Stub::async::ListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest* request, ::grpc::ClientReadReactor< ::serverstream::StreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::serverstream::StreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListValue_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::serverstream::StreamResponse>* StreamServer::Stub::AsyncListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::serverstream::StreamResponse>::Create(channel_.get(), cq, rpcmethod_ListValue_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::serverstream::StreamResponse>* StreamServer::Stub::PrepareAsyncListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::serverstream::StreamResponse>::Create(channel_.get(), cq, rpcmethod_ListValue_, context, request, false, nullptr);
}

StreamServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamServer_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StreamServer::Service, ::serverstream::SimpleRequest, ::serverstream::StreamResponse>(
          [](StreamServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::serverstream::SimpleRequest* req,
             ::grpc::ServerWriter<::serverstream::StreamResponse>* writer) {
               return service->ListValue(ctx, req, writer);
             }, this)));
}

StreamServer::Service::~Service() {
}

::grpc::Status StreamServer::Service::ListValue(::grpc::ServerContext* context, const ::serverstream::SimpleRequest* request, ::grpc::ServerWriter< ::serverstream::StreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace serverstream

