// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_stream.proto
// Original file comments:
// protocol buffer 协议版本
#ifndef GRPC_server_5fstream_2eproto__INCLUDED
#define GRPC_server_5fstream_2eproto__INCLUDED

#include "server_stream.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace serverstream {

// 服务端流式rpc
class StreamServer final {
 public:
  static constexpr char const* service_full_name() {
    return "serverstream.StreamServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::serverstream::StreamResponse>> ListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::serverstream::StreamResponse>>(ListValueRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstream::StreamResponse>> AsyncListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstream::StreamResponse>>(AsyncListValueRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstream::StreamResponse>> PrepareAsyncListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstream::StreamResponse>>(PrepareAsyncListValueRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest* request, ::grpc::ClientReadReactor< ::serverstream::StreamResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::serverstream::StreamResponse>* ListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::serverstream::StreamResponse>* AsyncListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::serverstream::StreamResponse>* PrepareAsyncListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::serverstream::StreamResponse>> ListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::serverstream::StreamResponse>>(ListValueRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstream::StreamResponse>> AsyncListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstream::StreamResponse>>(AsyncListValueRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstream::StreamResponse>> PrepareAsyncListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstream::StreamResponse>>(PrepareAsyncListValueRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListValue(::grpc::ClientContext* context, const ::serverstream::SimpleRequest* request, ::grpc::ClientReadReactor< ::serverstream::StreamResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::serverstream::StreamResponse>* ListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request) override;
    ::grpc::ClientAsyncReader< ::serverstream::StreamResponse>* AsyncListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::serverstream::StreamResponse>* PrepareAsyncListValueRaw(::grpc::ClientContext* context, const ::serverstream::SimpleRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListValue_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ListValue(::grpc::ServerContext* context, const ::serverstream::SimpleRequest* request, ::grpc::ServerWriter< ::serverstream::StreamResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListValue() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListValue(::grpc::ServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/, ::grpc::ServerWriter< ::serverstream::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListValue(::grpc::ServerContext* context, ::serverstream::SimpleRequest* request, ::grpc::ServerAsyncWriter< ::serverstream::StreamResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListValue<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListValue() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::serverstream::SimpleRequest, ::serverstream::StreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::serverstream::SimpleRequest* request) { return this->ListValue(context, request); }));
    }
    ~WithCallbackMethod_ListValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListValue(::grpc::ServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/, ::grpc::ServerWriter< ::serverstream::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::serverstream::StreamResponse>* ListValue(
      ::grpc::CallbackServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListValue<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListValue() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListValue(::grpc::ServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/, ::grpc::ServerWriter< ::serverstream::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListValue() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListValue(::grpc::ServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/, ::grpc::ServerWriter< ::serverstream::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListValue(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListValue() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ListValue(context, request); }));
    }
    ~WithRawCallbackMethod_ListValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListValue(::grpc::ServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/, ::grpc::ServerWriter< ::serverstream::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ListValue(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ListValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ListValue() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::serverstream::SimpleRequest, ::serverstream::StreamResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::serverstream::SimpleRequest, ::serverstream::StreamResponse>* streamer) {
                       return this->StreamedListValue(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ListValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListValue(::grpc::ServerContext* /*context*/, const ::serverstream::SimpleRequest* /*request*/, ::grpc::ServerWriter< ::serverstream::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedListValue(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::serverstream::SimpleRequest,::serverstream::StreamResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ListValue<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ListValue<Service > StreamedService;
};

}  // namespace serverstream


#endif  // GRPC_server_5fstream_2eproto__INCLUDED
