; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --split_sections --debug -c -S --gnu -o.\objects\delay.s --depend=.\objects\delay.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I..\Src\App -I..\Src\Bsp -I..\Src\Doc -I..\Src\Libraries\CMSIS\CoreSupport -I..\Src\Libraries\CMSIS\DeviceSupport -I..\Src\Libraries\CMSIS\DeviceSupport\Startup -I..\Src\Libraries\STM32F4xx_StdPeriph_Driver\inc -I..\Src\uCOS\uC-CPU\ARM-Cortex-M4\RealView -I..\Src\uCOS\uC-CPU -I..\Src\uCOS\uC-LIB -I..\Src\uCOS\uC-LIB\Ports\ARM-Cortex-M4\RealView -I..\Src\uCOS\uCOS-III\Source -I..\Src\uCOS\uCOS-III\Ports\ARM-Cortex-M4\Generic\RealView -I..\Src\Sys -I.\RTE\_F407ZGT6 -ID:\Keil_v5\ARM\PACK\Keil\STM32F4xx_DFP\2.13.0\Drivers\CMSIS\Device\ST\STM32F4xx\Include -ID:\Keil_v5\ARM\CMSIS\Include -D__UVISION_VERSION=525 -DSTM32F407xx -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER --omf_browse=.\objects\delay.crf ..\Src\Sys\delay.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.Delay_Init||, CODE, READONLY, ALIGN=2

Delay_Init PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MVN      r0,#4
        BL       SysTick_CLKSourceConfig
        ASRS     r1,r4,#31
        ADD      r1,r4,r1,LSR #29
        UBFX     r1,r1,#3,#8
        LDR      r2,|L0.52|
        STRB     r1,[r2,#0]
        MOV      r0,r2
        LDRB     r0,[r0,#0]  ; fac_us
        ADD      r1,r0,r0,LSL #1
        RSB      r0,r1,r0,LSL #7
        MOV      r1,#0xffff
        AND      r0,r1,r0,LSL #3
        LDR      r1,|L0.56|
        STRH     r0,[r1,#0]
        POP      {r4,pc}
        ENDP

|L0.52|
        DCD      fac_us
|L0.56|
        DCD      fac_ms

        AREA ||i.delay_ms||, CODE, READONLY, ALIGN=1

delay_ms PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r0,#0x21c
        SDIV     r0,r4,r0
        UXTB     r6,r0
        MOV      r0,#0x21c
        SDIV     r1,r4,r0
        MLS      r0,r0,r1,r4
        UXTH     r5,r0
        B        |L1.42|
|L1.30|
        MOV      r0,#0x21c
        BL       delay_xms
        SUBS     r0,r6,#1
        UXTB     r6,r0
|L1.42|
        CMP      r6,#0
        BNE      |L1.30|
        CBZ      r5,|L1.54|
        MOV      r0,r5
        BL       delay_xms
|L1.54|
        POP      {r4-r6,pc}
        ENDP


        AREA ||i.delay_us||, CODE, READONLY, ALIGN=2

delay_us PROC
        MOV      r1,r0
        LDR      r2,|L2.72|
        LDRB     r2,[r2,#0]  ; fac_us
        MULS     r2,r1,r2
        MOV      r3,#0xe000e000
        STR      r2,[r3,#0x14]
        MOVS     r2,#0
        STR      r2,[r3,#0x18]
        MOV      r2,r3
        LDR      r2,[r2,#0x10]
        ORR      r2,r2,#1
        STR      r2,[r3,#0x10]
        NOP      
|L2.30|
        MOV      r2,#0xe000e000
        LDR      r0,[r2,#0x10]
        AND      r2,r0,#1
        CBZ      r2,|L2.50|
        AND      r2,r0,#0x10000
        CMP      r2,#0
        BEQ      |L2.30|
|L2.50|
        MOV      r2,#0xe000e000
        LDR      r2,[r2,#0x10]
        BIC      r2,r2,#1
        MOV      r3,#0xe000e000
        STR      r2,[r3,#0x10]
        MOVS     r2,#0
        STR      r2,[r3,#0x18]
        BX       lr
        ENDP

|L2.72|
        DCD      fac_us

        AREA ||i.delay_xms||, CODE, READONLY, ALIGN=2

delay_xms PROC
        MOV      r1,r0
        LDR      r2,|L3.72|
        LDRH     r2,[r2,#0]  ; fac_ms
        MULS     r2,r1,r2
        MOV      r3,#0xe000e000
        STR      r2,[r3,#0x14]
        MOVS     r2,#0
        STR      r2,[r3,#0x18]
        MOV      r2,r3
        LDR      r2,[r2,#0x10]
        ORR      r2,r2,#1
        STR      r2,[r3,#0x10]
        NOP      
|L3.30|
        MOV      r2,#0xe000e000
        LDR      r0,[r2,#0x10]
        AND      r2,r0,#1
        CBZ      r2,|L3.50|
        AND      r2,r0,#0x10000
        CMP      r2,#0
        BEQ      |L3.30|
|L3.50|
        MOV      r2,#0xe000e000
        LDR      r2,[r2,#0x10]
        BIC      r2,r2,#1
        MOV      r3,#0xe000e000
        STR      r2,[r3,#0x10]
        MOVS     r2,#0
        STR      r2,[r3,#0x18]
        BX       lr
        ENDP

|L3.72|
        DCD      fac_ms

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=1

fac_us
        DCB      0x00,0x00
fac_ms
        DCW      0x0000

;*** Start embedded assembler ***

#line 1 "..\\Src\\Sys\\delay.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___7_delay_c_19c669a7____REV16|
#line 138 "..\\Src\\Libraries\\CMSIS\\CoreSupport\\core_cmInstr.h"
|__asm___7_delay_c_19c669a7____REV16| PROC
#line 139

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___7_delay_c_19c669a7____REVSH|
#line 153
|__asm___7_delay_c_19c669a7____REVSH| PROC
#line 154

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___7_delay_c_19c669a7____RRX|
#line 328
|__asm___7_delay_c_19c669a7____RRX| PROC
#line 329

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT Delay_Init [CODE]
        EXPORT delay_ms [CODE]
        EXPORT delay_us [CODE]
        EXPORT delay_xms [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT SysTick_CLKSourceConfig [CODE]

        KEEP fac_us
        KEEP fac_ms

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
