; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --split_sections --debug -c -S --gnu -o.\objects\sys.s --depend=.\objects\sys.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I..\Src\App -I..\Src\Bsp -I..\Src\Doc -I..\Src\Libraries\CMSIS\CoreSupport -I..\Src\Libraries\CMSIS\DeviceSupport -I..\Src\Libraries\CMSIS\DeviceSupport\Startup -I..\Src\Libraries\STM32F4xx_StdPeriph_Driver\inc -I..\Src\uCOS\uC-CPU\ARM-Cortex-M4\RealView -I..\Src\uCOS\uC-CPU -I..\Src\uCOS\uC-LIB -I..\Src\uCOS\uC-LIB\Ports\ARM-Cortex-M4\RealView -I..\Src\uCOS\uCOS-III\Source -I..\Src\uCOS\uCOS-III\Ports\ARM-Cortex-M4\Generic\RealView -I..\Src\Sys -I.\RTE\_F407ZGT6 -ID:\Keil_v5\ARM\PACK\Keil\STM32F4xx_DFP\2.13.0\Drivers\CMSIS\Device\ST\STM32F4xx\Include -ID:\Keil_v5\ARM\CMSIS\Include -D__UVISION_VERSION=525 -DSTM32F407xx -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER --omf_browse=.\objects\sys.crf ..\Src\Sys\sys.c]
        THUMB
        PRESERVE8

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "..\\Src\\Sys\\sys.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___5_sys_c_WFI_SET____REV16|
#line 138 "..\\Src\\Libraries\\CMSIS\\CoreSupport\\core_cmInstr.h"
|__asm___5_sys_c_WFI_SET____REV16| PROC
#line 139

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___5_sys_c_WFI_SET____REVSH|
#line 153
|__asm___5_sys_c_WFI_SET____REVSH| PROC
#line 154

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___5_sys_c_WFI_SET____RRX|
#line 328
|__asm___5_sys_c_WFI_SET____RRX| PROC
#line 329

 rrx r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |WFI_SET|
#line 6 "..\\Src\\Sys\\sys.c"
|WFI_SET| PROC
#line 7

 WFI
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |INTX_DISABLE|
#line 11
|INTX_DISABLE| PROC
#line 12

 CPSID I
 BX LR 
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |INTX_ENABLE|
#line 17
|INTX_ENABLE| PROC
#line 18

 CPSIE I
 BX LR 
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |MSR_MSP|
#line 24
|MSR_MSP| PROC
#line 25

 MSR MSP, r0  
 BX r14
	ENDP

;*** End   embedded assembler ***

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
